### PR TITLE
Sync with upstream/master

### PR DESCRIPTION
**Pull request by naveg**
The only conflict of note was that our modifications in `Redis::Instrumentation` are now moved to `Redis::TraceMiddleware`

Diff between this branch and upstream: https://github.com/DataDog/dd-trace-rb/compare/master...Appboy:dd-trace-rb:naveg/sync-upstream

### CODE REVIEW

**Review by jasonpenny — CHANGES_REQUESTED** [review]
This has the same problem that Zach's `1.18` PR had https://github.com/Appboy/dd-trace-rb/pull/15#pullrequestreview-1801125015

also, the CODEOWNERS file should not have multiple lines for `* ...`
image

**Comment by naveg** [comment]
Missed #15, thanks

**Comment by naveg** [comment]
OK, I think it should be fixed now.

> Also, it looks like v1.18 changes the default of some options (for redis, and maybe others), these should probably be audited or deploying this could change observability

I skimmed the changelog and these were the items that appeared relevant to us:

```
# Changelog

## [1.16.0] - 2023-11-03

### Changed

* Tracing: Redis - Omit command arguments from span.resource by default ([#3235][])

## [1.15.0] - 2023-10-09

### Changed

* Tracing: `dalli` disable memcached command tag by default ([#3171][])

### Fixed

* Tracing: Fix `rails.cache.backend` span tag with multiple stores ([#3060][])
```

I'll deploy this to a PCE and do some additional testing

**Review by jasonpenny — APPROVED** [review]
I have never trusted their changelog (it didn't mention anything the last time we missed defaults changing)

**Pull request merged**
