### PR TITLE
Merge v0.54.2

### PR DESCRIPTION
**Pull request by isturdy**
I'd like to update to catch the rspec integration introduced in 0.53.

How should this be tested?

### CODE REVIEW

**Review by jasonpenny — APPROVED** [review]
The fork changes still look good https://github.com/DataDog/dd-trace-rb/compare/v0.54.2..Appboy:update-0.54.2?w=1

I don't remember if PCEs have datadog traces hooked up, but if not, I think we have generally just tested with olaf+sweeney

@zachmccormick do you have a better way?

**Comment by zachmccormick** [comment]
Sometimes I ssh into a sweeney node and just update the gemfile there, bundle install, restart the processes, and see if its still reporting the right data. if i'm wrong i just hose the node

**Review by mohit-bansal-braze — APPROVED** [review]

**Comment by isturdy** [comment]
It seems to fail to build on our servers: https://buildkite.com/braze/branch-platform-build-images/builds/3759#0a9e687e-03a5-4e1a-b44d-18bc96b6c010

I'm not quite sure why yet; it builds and installs for dashboard locally without problem.

**Comment by jasonpenny** [comment]
> It seems to fail to build on our servers:

This is in the output
```
Preparing to build the ddtrace native extension
```

this requires the native build toolchain, so this gem will need to be added to https://github.com/appboy/platform-image-base

**Comment by isturdy** [comment]
Tested in a https://github.com/Appboy/platform/tree/plati-127-upgrade-dd-trace PCE--traces show up in DD. The failing tests are a single case we don't touch--I incline to leave them alone to avoid complicating the next merge.

**Pull request merged**
