### PR TITLE
Merge 0.43.0 into the Braze fork

### PR DESCRIPTION
**Pull request by jasonpenny**
This is a quick attempt at merging upstream 0.43.0 into the Braze fork.
I think we need to do better at keeping our custom forks nearer to the upstream release version.

There are some things mentioned in the changelog that would probably be worthwhile, like improved memory usage:
https://github.com/DataDog/dd-trace-rb/blob/master/CHANGELOG.md#0430---2020-11-18

The patch from https://github.com/Appboy/dd-trace-rb/commit/9fb56bffead00d4f078b561bc0571ff95a58457e was removed since 4xx as errors are now covered by the upstream `error_statuses` config (and default to not error for 4xx)

Upstream also added a kafka integration, but it looks like it's based on a different gem? I don't know how to modify our implementation or migrate to theirs, so I kept our files in this branch and they appear as heavy file modifications.

Our pg integration still exists in this branch, but I haven't tested it. Is there a reason not to contribute this to the upstream project?

Our fork changes after this PR can be seen with https://github.com/DataDog/dd-trace-rb/compare/v0.43.0...Appboy:braze-merge-0.43.0?w=1

### CODE REVIEW

**Review by mkigikm — COMMENTED** [review]
I think you have to add a configuration for `error_statuses`, the default look like it will report an error for 4xx to me.

**Comment by jasonpenny** [comment]
> I think you have to add a configuration for error_statuses, the default look like it will report an error for 4xx to me.

I was originally confused when migrating the 4xx tests still passed after removing the 4xx code change

The default is `nil` which falls back to ERROR_RANGE

https://github.com/Appboy/dd-trace-rb/blob/4abaf03cdb8f297d9421be10656a3d9449d8e205/lib/ddtrace/contrib/status_code_matcher.rb#L61-L62

https://github.com/Appboy/dd-trace-rb/blob/4abaf03cdb8f297d9421be10656a3d9449d8e205/lib/ddtrace/ext/http.rb#L5

**Comment by mattdisipio** [comment]
The changes I made look good, I'm unsure as to why the pg changes weren't introduced upstream

**Comment by jasonpenny** [comment]
@zachmccormick can you take a look at this?

**Comment by zachmccormick** [comment]
I tried introducing the PG changes but their testing framework IIRC is a monster that I could not get to run locally

**Comment by zachmccormick** [comment]
this looks fine to me

**Review by zachmccormick — APPROVED** [review]

**Comment by zachmccormick** [comment]
I've just been pulling the branch in, then rebasing our 3-4 commits on top of it, instead of merging in upstream changes, but this works too

**Comment by zachmccormick** [comment]
wanna block out some time to do this together next week?

**Pull request merged**
